### ISSUE TITLE
Program too zoomed in

### ISSUE THREAD

**Issue by RikKoningen** [Noxde/Bloodborne-save-editor#10]
I'm unable to resize the program and the interface is very zoomed in in such a way that I cannot use the interface as most of the buttons are outside of the accessible window.

**Comment by RikKoningen** [comment]
The resolution of my main monitor is 2560x1440 (144hz) and I used the windows executable downloaded yesterday. According to the file 0.2.0_x64 is the version I used.

**Comment by Noxde** [comment]
I guess you are setting the scale to something higher to 100% Having the width and height fixed is not ideal but I made the ui with only that size in mind. I'll attach here a version that is resizable in a bit, not sure if that will fix anything but at least you can try that while we look into that

**Comment by Noxde** [comment]
Here you go https://www.mediafire.com/file/tlpn0gn7im7b2pq/Bloodborne_Save_Editor_0.2.0_x64-setup.exe/file
Couldn't attach it here directly, hopefully that kinda fixes it for you. We'll look into it though

**Comment by RikKoningen** [comment]
That does fix my issue thank you very much! I had tested application scaling that windows has and it made no difference so I assumed that wasn't the issue. But it turns out text scale was the problem so that is also a potential fix though the modified version is a lot better for my use. So thanks again for the speedy responses and the fix!
