### ISSUE TITLE
Missing items on weapons/armors replace tab

### ISSUE THREAD

**Issue by BraianLDC** [Noxde/Bloodborne-save-editor#16]
Church Cannon and Wooden Shield are missing on weapon replace menu

Constable Gloves and Trousers also missing on armor replacement tab

Feature request:
Would it be possible to add replacement of a weapon for armors / and gems for runes?

**Comment by Noxde** [comment]
Thanks for letting me know, I'll make sure to add them.

It could be possible to replace a weapon with an armor but not with a rune, weapons and armors share the same structure but runes are completely different. I should really try it first though but I'd say it is possible

**Comment by BraianLDC** [comment]
added 2 armor items i noticed missing on the armor replacement feature aswell

**Comment by Noxde** [comment]
Please open a new issue for the feature request, the items have been added on the latest release [0.4.0](https://github.com/Noxde/Bloodborne-save-editor/releases/tag/0.4.0)
