### ISSUE TITLE
Save Editor crashes when loading save

### ISSUE THREAD

**Issue by Zhinakin** [Noxde/Bloodborne-save-editor#17]
Used the editor fine, but now it just crashes whenever i try to load the save. It still makes a backup, but the program terminates when it loads the save.

**Comment by Noxde** [comment]
Could you send me the save? I can try it on the dev version so I can see the error

**Comment by Zhinakin** [comment]
I apologize, i reordered some files, and misplaced the resource folder, that's the reason for the crash. Again my apologies for wasting your time.

**Comment by Noxde** [comment]
> I apologize, i reordered some files, and misplaced the resource folder, that's the reason for the crash. Again my apologies for wasting your time.

No worries, glad that its working!
