### ISSUE TITLE
would be nice to be able to edit character storage box

### ISSUE THREAD

**Issue by watashiwalsh** [Noxde/Bloodborne-save-editor#19]
it has been very nice being able to update items that show up in your character inventory, however, it would be cool to also have access to items that are in your storage. i don't know how hard this is, but it would certainly be useful.
I haven't verified if this is just the case for consumables, but having access to any storage items (gems, weapons, armor, etc) would be useful.

one problem this lack of access causes is that if i want to have (for example) 99 greatone coldblood (gocb) in BOTH my inventory and storage, i have to:
1 - load save into save editor
2 - use editor to set my inventory gocb to 99
3 - load my save back onto console
4 - transfer 98 gocb to storage (since i have to leave one in my inventory to access it in step 6)
5 - load my save back into the save editor
6 - set the one remaining inventory gocb to 99
7 - load my save back onto console
THEN, if i actually want 99 in both inventory and storage (currently there is 99 in my inventory and 98 in my storage) i would have to do steps 4-7 again to get one more gocb to storage

a first world problem, but worth the effort i think, since many people will be using the editor to give themselves max inventory

**Comment by Noxde** [comment]
Available on latest release [0.4.0](https://github.com/Noxde/Bloodborne-save-editor/releases/tag/0.4.0)
