### ISSUE TITLE
Cant see items

### ISSUE THREAD

**Issue by BananaCat0** [Noxde/Bloodborne-save-editor#22]
i have the issue where i cant see my weapons or upgrade materials when using the save editor.
i can still see my gems and runes but basically nothing else.

**Comment by Noxde** [comment]
Do you see your character's name on the character tab? and what is your game id?

**Comment by BananaCat0** [comment]
Hi first of all thanks for the fast reply.
i can see the character name at the top and im not sure what you mean by game id as im not the most tech knoledgeable person

**Comment by Noxde** [comment]
By character tab I meant here, the name at the top is the file name
![image](https://github.com/user-attachments/assets/361535f5-c5e7-47a5-bc32-a5e80d0db192)

If you got your save from your playstation, the game id is the last thing here, in my case CUSA00900
![image](https://github.com/user-attachments/assets/b9eb7017-708e-479a-b732-8d8284c30844)

If you are using shadps4 you should see the game id on the emulator where you can select the game, it should be CUSA and some numbers

**Comment by BananaCat0** [comment]
ok i understand now, the game id i see is CUSA00207. idk if it's important but i used save wizard to get my save

**Comment by Noxde** [comment]
Its probably that then, I think the saves from that id are a bit different than the rest, we'll have to look into that at some point. I'll update the readme to reflect this. Sorry about that

**Comment by BananaCat0** [comment]
i actually think it's a me issue as i noticed when looking at the pic you sent that my version didn't have the face export/import and because of that i realised i dowloaded an earlier version.

**Comment by Noxde** [comment]
All the versions handle the saves the same way so you're good, its an issue with the editor because the saves from that id have a different structure and we never looked into it since we didn't use any saves from that id and the other ones are all the same

**Comment by BananaCat0** [comment]
hmm weird as after dowloading version 4.0 i can see everything in my inventory not just my gems and runes

**Comment by Noxde** [comment]
> hmm weird as after dowloading version 4.0 i can see everything in my inventory not just my gems and runes
Well, thats even weirder, what is the name of the file you are opening? is it userdataXXXX or a backup?

**Comment by BananaCat0** [comment]
it's just an exported save wizard file so userdata0001

**Comment by Noxde** [comment]
Could you send me the save file so I can take a look some other day

**Comment by BananaCat0** [comment]
[Sir Slice alot.zip](https://github.com/user-attachments/files/18138274/Sir.Slice.alot.zip)
here you go, hope i did it right

**Comment by Noxde** [comment]
Seems to be working fine for me
![{3674B48B-8F9C-4912-AE79-AB1B13424169}](https://github.com/user-attachments/assets/c2246fe6-ffa5-41df-a79a-f8883feef9e4)

I can see runes and gems too

**Comment by Noxde** [comment]
I can send you the installer for the one Im using but it should be the same thing

**Comment by BananaCat0** [comment]
i wrote it a bit weird but i meant that now i could see other stuff than just my gems and runes.
but it's weird you can't see armor and key items as i dont have that issue now

**Comment by Noxde** [comment]
I opened the debug version I have and everything works fine so I guess its just something to do with the release I got installed

**Comment by BananaCat0** [comment]
i have one last question, is there a discord or anyting alike for if i have any future questions?

**Comment by Noxde** [comment]
This server should be fine
https://discord.gg/xcier-752300555355029566
After joining just follow this link for the bloodborne channel
https://discord.com/channels/752300555355029566/1230691142576771213

I would prefer this over dms
