### ISSUE TITLE
Items are not being replaced.

### ISSUE THREAD

**Issue by thoreriksson** [Noxde/Bloodborne-save-editor#23]
The problem is quite self-explanatory. The items aren't being replaced. Not even the blood vials or silver bullets. 
It may just be a problem on my end. I'll keep on experimenting and let you know if anything changes. 
Do look into it for me. I do so love this game and I'm finally close to being able to control what weapon I start out with, and it sounds real fun. 

God be with you.

Save ID = CUSA00207

**Comment by thoreriksson** [comment]
NVM. The problem was that the saves had (1) in their name. 
Otherwise, for me, the software works completely fine.

**Comment by Noxde** [comment]
Hey, could you send the save file that you are having problems with so I can look into it?

Thanks.

**Comment by Noxde** [comment]
Got an email saying that its actually working, should I close this issue?

**Comment by thoreriksson** [comment]
> Got an email saying that its actually working, should I close this issue?

I'm sorry for the confusion. I had problems before porting the save back to the PS5, but I solved that issue. The issue with that there were (1) in the same names which did so that the PS5 didn't recognize the files. 

The Program (Bloodborne save editor) works.  It successfully opens and mods the file (I think.). However, when the files are encrypred, and replace the game saves on the PS5. No changes have been made.  

This is the unmodified save (The file format isn't supported so I put .gif at the end of the name. Removing the .gif in the name should revert it to its original form. If not and I am proven to be dumb, then I could possibly email you the file. )
![userdata0007](https://github.com/user-attachments/assets/17199c67-6263-46b9-8913-4464095c3dea)


This is the modified one
![userdata0007](https://github.com/user-attachments/assets/af1ae377-ee91-4892-8f95-c615c3a9b024)

**Comment by thoreriksson** [comment]
Ok. I got it to work. Don't ask why. It just works now. Idk why. Idk how. 

Took like 5 attempts of just encrypting and replacing.
