### ISSUE TITLE
Errors Encountered in Current Build.

### ISSUE THREAD

**Issue by mrbrisco** [Noxde/Bloodborne-save-editor#6]
Hello,

First off thank you for the amazing tool, editing hex codes was too much of a pain and this quite literally has been a game changer!

All saved games were decrypted using save wizard and repackaged using the advanced option in there as well all on Windows 11.

On to the errors I encountered and how to replicate:

1. When altering any key item to the "Yahrnam Messenger Hat" the item would show up as modified in the save editor list, but it would not show up in the game at all.
2. Certain Gem icons are not supported even if they are real in game effects (HP Recover as main effect on any gem type will show a null icon), (Blood ATK on Triangle gem type shows null), (Increase Stamina usage curse does not put Cursed effect icon or name on any gem type).
~~3. Gems of the same type after being made and showing up on the edit list are not available for selection in game. (If you made 2 Nourishing Radials, only the 1st gem listed and the second is missing entirely, same for any other types of the same kind).~~

Striking through the third issue, as it has been **RESOLVED**. The issue seems to be the editor does not differentiate between gems stored in your inventory vs gems stored in your storage, so I found the missing gems after performing various tests. Basically they were in my storage. However the top 2 issues remain.

Please let me know if you would like any further feedback.

Thank you again!

**Comment by Noxde** [comment]
Thank you for the feedback, we'll look into those things

**Comment by ClixzyFN** [comment]
can you please add a way to change the name

**Comment by Noxde** [comment]
> **[ClixzyFN](/ClixzyFN) ** commented

We plan on adding that

**Comment by bawsdeep** [comment]
> can you please add a way to change the name



> can you please add a way to change the name

would recommend on adding the name in the title next to the save number so people have an easier time finding the right char in the saves

**Comment by WonderSquid** [comment]
As far as I'm aware, the DLC messenger skins can't be added via save editing of any kind, unfortunately. The game has an external check where it looks to see if you qualify to have them in the first place upon load (ie if you've downloaded the skin DLC in question), and removes them accordingly if you don't. Nobody's ever successfully edited them in via save edits alone.

**Comment by Noxde** [comment]
> Striking through the third issue, as it has been **RESOLVED**. The issue seems to be the editor does not differentiate between gems stored in your inventory vs gems stored in your storage, so I found the missing gems after performing various tests. Basically they were in my storage. However the top 2 issues remain.

Thanks for testing that out, I haven't checked how to diferentiate between gems in the inventory and gems in the storage and they're all together at the start of the save, I'll keep that in mind

**Comment by bawsdeep** [comment]
> As far as I'm aware, the DLC messenger skins can't be added via save editing of any kind, unfortunately. The game has an external check where it looks to see if you qualify to have them in the first place upon load (ie if you've downloaded the skin DLC in question), and removes them accordingly if you don't. Nobody's ever successfully edited them in via save edits alone.

Yeah they added the DLC checks after releasing the DLC there was a bug in the early days of the DLCsthat allowed people who havent purchased the DLC to still gain acess to the DLC by summoning a second player with the key item

**Comment by Noxde** [comment]
Yea, just tried it. Should I remove it from the items on the editor?

**Comment by Noxde** [comment]
Solved on latest release. 
Cant fix the first issue since there is a check for that in game, might remove it from the items later
