### ISSUE TITLE
Gem replace 

### ISSUE THREAD

**Issue by demonslayer228** [Noxde/Bloodborne-save-editor#8]
Why i can't replace runes?
Like i need a milkweed rune instead other rune.
Or is there a rune spawner?

**Comment by Noxde** [comment]
> Why i can't replace runes? Like i need a milkweed rune instead other rune. Or is there a rune spawner?

You can change the effects of the runes, the first effect determines the name and image but you could just have 6 effects on a rune

**Comment by demonslayer228** [comment]
> > Why i can't replace runes? Like i need a milkweed rune instead other rune. Or is there a rune spawner?
> 
> You can change the effects of the runes, the first effect determines the name and image but you could just have 6 effects on a rune, if the rune is an oath rune change the type as well so the name and image work.
> 
> Check the gif on the readme: ![image](https://github.com/Noxde/Bloodborne-save-editor/raw/main/assets/edit_rune.gif) [ ![image](https://github.com/Noxde/Bloodborne-save-editor/raw/main/assets/edit_rune.gif) ](https://github.com/Noxde/Bloodborne-save-editor/raw/main/assets/edit_rune.gif) [ ](https://github.com/Noxde/Bloodborne-save-editor/raw/main/assets/edit_rune.gif)

Got it, thank you.
I thought, that the first effect = name of a milkweed.
