### ISSUE TITLE
Kos Parasite doesn't work

### ISSUE THREAD

**Issue by demonslayer228** [Noxde/Bloodborne-save-editor#9]
Well i replace weapon to Kos Parasite. I have 20 Arcane and Milkweed rune, but i still fighting with my fists. Checked with original Kos Parasite on another save and it works.

**Comment by Noxde** [comment]
I'll look into it, thanks for letting us know

**Comment by Noxde** [comment]
Managed to make it work, the rune needs 2 more effects for the Kos parasite to work, both are called "??". Search for "??" and add the first one and the second one, then it will work

**Comment by demonslayer228** [comment]
> Managed to make it work, the rune needs 2 more effects for the Kos parasite to work, both are called "??". Search for "??" and add the first one and the second one, then it will work

Yes, it works. Thank you.
